---
title: "Current Projects"
output: html_document
---
<style type="text/css">
  .title {display:none;}
  
  .projects {padding-left: 10px;padding=top: 10px}
  
</style>

<div class="projects"> 
  <h3>Math Experts</h3> 
  <p>"What is the body doing, when the body does mathematics?"  When we imagine what creative problem solving looks like, we may envision something similar to Auguste Rodin's "The Thinker." However, when 8 PhD level mathematicians in their natural environment (at a black board with a piece of chalk) begin solving various problems, we see a combination of gesture, movement, and niche construction. The Math Experts video corpus provides us new evidence of what creative thinking truly looks like and inspires new questions about the impact of proximity change. </p> 

  <h3>Creative Movement</h3>
  <p>A continuation of the Math Experts project, we are seeking non-correlation evidence of how proximity change and having information accessible in our visual field can self generate hints and inspire "aha!" moments. Participants come in person to the lab and solve 2 related puzzles in one of 3 conditions: close, far, or flexible. Those in the close condition are prevented from seeing the previous puzzle imagery while the far condition easily allows access to both. The flexible condition allows participants to chose their own method of proximity change. We predict those in the far and flexible conditions will solve the 2nd puzzle more often and faster than those in the close condition. Data collection is currently ongoing with a planned N = 160. </p>

  <h3>NoisyP6</h3>
  <p>In accordance with the Noisy-Channel framework, listeners are constantly filtering various sources of noise such as speaker errors, misinterpretation, and environmental noise in order to extract intended meanings from a speakers. Comprehenders are more likely to understand the intended meaning if: 1. the meaning of the speaker’s error is easily recoverable and 2. the environmental noise rate is perceived to be high, allowing the comprehender to expect these errors in advance. Online real-time processing involves the use of N400 and P600 ERP components at varying amplitudes to determine the probability of noisy-channel inferences. This study aims to replicate and expand on previous research by investigating whether the sizes of N400 and P600 effects are impacted by the noise rate. This is being accomplished by manipulating error proportions in non-target sentences between-subjects, and manipulating error type (semantic, syntactic, recoverable) within-subjects. Data collection is currently ongoing with a planned N = 48. </p>

  <h3>ATLAS</h3>
  <p>The Abstract Thought and Language Across Space (ATLAS) databank is a compendium of published research on cross-cultural variability in the conceptualization of space, time, and number. Specifically, it collects published studies involving non-English-speaking participants that investigate: (1) spatial frames of reference, (2) spatial representations of time, and (3) spatial representations of number. The formation of this databank is actively in progress .</p>
</div>
